name = "Beep"
uuid = "523ff9b5-acc8-40d7-b2fd-2928fbc3bb4b"
authors = ["Aru Bhardwaj <arubhardwaj@pm.me>"]
version = "0.1.0"

[deps]
WAV = "8149f6b0-98f6-5db9-b78f-408fbbb8ef88"

[compat]
WAV = "1.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
